<#
.SYNOPSIS
    Run independent-start grand-canonical Bose-Hubbard audit jobs in parallel.
.DESCRIPTION
    Fresh creates low, central, and high particle-number starts for every
    requested (L,beta) point. Resume continues their checkpoints. Production
    resets measurements without resetting the worldlines and saves a numbered
    result block. The script limits the batch to this desktop's 24 physical cores.
.EXAMPLE
    .\scripts\run_gc_bkt_audit.ps1 -Mode Fresh -AuditName gc_bkt_L32 -Sizes 32 -Betas 0.24,0.27,0.29,0.32 -Mu -3.53 -ProcessesPerChain 2 -RuntimeLimit 600
.EXAMPLE
    .\scripts\run_gc_bkt_audit.ps1 -Mode Production -AuditName gc_bkt_L32 -ProductionIndex 1
#>
[CmdletBinding()]
param(
    [ValidateSet('Prepare', 'Fresh', 'Resume', 'Production')]
    [string]$Mode = 'Prepare',
    [string]$AuditName = 'gc_bkt_audit',
    [int[]]$Sizes = @(32),
    [double[]]$Betas = @(0.24, 0.27, 0.29, 0.32),
    [double]$Mu = -3.53,
    [ValidateRange(1, 24)] [int]$ProcessesPerChain = 2,
    [ValidateRange(1, 2147483647)] [int]$RuntimeLimit = 600,
    [ValidateRange(10, 2147483647)] [int]$Sweeps = 20000000,
    [ValidateRange(0, 2147483647)] [int]$Thermalization = 1000,
    [ValidateRange(1, 2147483647)] [int]$Nmeasure2 = 1000,
    [ValidateRange(0.01, 100.0)] [double]$CenterDensity = 2.4,
    [ValidateRange(0.05, 0.8)] [double]$StartSpread = 0.25,
    [ValidateRange(0, 4294967295)] [uint32]$BaseSeed = 270000,
    [ValidateRange(1, 999)] [int]$ProductionIndex = 1,
    [string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$runner = Join-Path $PSScriptRoot 'run_rb87_bkt64.ps1'
$safeName = [regex]::Replace($AuditName, '[^A-Za-z0-9_-]', '_')
if (-not $safeName) { throw 'AuditName must contain a letter, number, underscore, or hyphen.' }
if (-not $OutputDirectory) { $OutputDirectory = Join-Path $repoRoot "results\$safeName" }
$outputRoot = [IO.Path]::GetFullPath($OutputDirectory)
$parameterDirectory = Join-Path $outputRoot 'parameters'
$jobRoot = Join-Path $outputRoot 'jobs'
$manifestPath = Join-Path $outputRoot 'audit_manifest.csv'
$invariant = [Globalization.CultureInfo]::InvariantCulture

if (-not (Test-Path -LiteralPath $runner -PathType Leaf)) { throw "Runner not found: $runner" }

function Format-Number {
    param([double]$Value)
    return $Value.ToString('G17', $invariant)
}

function Format-Label {
    param([double]$Value)
    return $Value.ToString('0.######', $invariant).Replace('-', 'm').Replace('.', 'p')
}

function Write-ParameterFile {
    param(
        [Parameter(Mandatory)] [string]$Path,
        [Parameter(Mandatory)] [int]$Size,
        [Parameter(Mandatory)] [double]$Beta,
        [Parameter(Mandatory)] [int]$InitialParticles,
        [Parameter(Mandatory)] [uint32]$Seed
    )

    $lines = @(
        '# Generated by scripts\run_gc_bkt_audit.ps1. Do not edit after Fresh.',
        'model = "BoseHubbard"',
        "runtimelimit = $RuntimeLimit",
        "sweeps = $Sweeps",
        "thermalization = $Thermalization",
        "Lx = $Size",
        "Ly = $Size",
        'Lz = 1',
        'pbcx = 1',
        'pbcy = 1',
        'pbcz = 0',
        't_hop = 1.0',
        'U_on = 0.152',
        'V_nn = 0.0',
        ('mu = ' + (Format-Number $Mu)),
        ('beta = ' + (Format-Number $Beta)),
        'nmax = 16',
        'E_off = 1.0',
        'canonical = -1',
        '# canonical_window is parsed for a shared file schema but ignored by the ordinary grand-canonical executable.',
        'canonical_window = 0.5',
        "initial_particle_number = $InitialParticles",
        'initial_occupancy = 2',
        "seed = $Seed",
        'Ntest = 1000000',
        'Nsave = 100000000',
        'Nmeasure = 1',
        "Nmeasure2 = $Nmeasure2",
        'C_worm = 2.0',
        'p_insertworm = 1.0',
        'p_moveworm = 0.4',
        'p_insertkink = 0.3',
        'p_deletekink = 0.2',
        'p_glueworm = 0.1',
        'outputfile = "result.out.h5"',
        'checkpoint = "checkpoint.clone.h5"'
    )
    [IO.File]::WriteAllText($Path, ($lines -join [Environment]::NewLine) + [Environment]::NewLine, [Text.UTF8Encoding]::new($false))
}

function New-AuditManifest {
    if ($Sizes.Count -eq 0 -or $Betas.Count -eq 0) { throw 'Provide at least one size and one beta.' }
    if (@($Sizes | Select-Object -Unique).Count -ne $Sizes.Count) {
        throw 'Sizes must not contain duplicates.'
    }
    $betaLabels = @($Betas | ForEach-Object { Format-Label $_ })
    if (@($betaLabels | Select-Object -Unique).Count -ne $betaLabels.Count) {
        throw 'Beta values must be unique at the six-decimal job-label precision.'
    }
    foreach ($size in $Sizes) {
        if ($size -lt 3) { throw "Periodic square lattices require L >= 3: $size" }
    }
    foreach ($beta in $Betas) {
        if ([double]::IsNaN($beta) -or [double]::IsInfinity($beta) -or $beta -le 0) { throw "Beta must be finite and positive: $beta" }
    }
    if ([double]::IsNaN($Mu) -or [double]::IsInfinity($Mu)) { throw 'Mu must be finite.' }

    New-Item -ItemType Directory -Force $outputRoot, $parameterDirectory, $jobRoot | Out-Null
    $profiles = @(
        [pscustomobject]@{ Name='low'; Factor=(1.0 - $StartSpread) },
        [pscustomobject]@{ Name='mid'; Factor=1.0 },
        [pscustomobject]@{ Name='high'; Factor=(1.0 + $StartSpread) }
    )
    $rows = @()
    $index = 0
    foreach ($size in $Sizes) {
        foreach ($beta in $Betas) {
            foreach ($profile in $profiles) {
                $sites = [double]$size * [double]$size
                $initialParticles = [int][math]::Round($CenterDensity * $profile.Factor * $sites, 0, [MidpointRounding]::AwayFromZero)
                if ($initialParticles -gt 16 * $sites) {
                    throw "Generated initial N=$initialParticles exceeds nmax=16 on L=$size."
                }
                $seed64 = [uint64]$BaseSeed + [uint64]($index * 1000)
                if ($seed64 -gt [uint32]::MaxValue) { throw 'Generated seed exceeds uint32.' }
                $seed = [uint32]$seed64
                $betaLabel = Format-Label $beta
                $jobName = 'L{0:D3}_beta{1}_{2}' -f $size, $betaLabel, $profile.Name
                $parameterPath = Join-Path $parameterDirectory "$jobName.ini"
                $jobDirectory = Join-Path $jobRoot $jobName
                Write-ParameterFile -Path $parameterPath -Size $size -Beta $beta -InitialParticles $initialParticles -Seed $seed
                $parameterHash = (Get-FileHash -LiteralPath $parameterPath -Algorithm SHA256).Hash
                $rows += [pscustomobject][ordered]@{
                    JobName = $jobName
                    Size = $size
                    Beta = Format-Number $beta
                    Mu = Format-Number $Mu
                    Start = $profile.Name
                    InitialParticles = $initialParticles
                    Seed = $seed
                    Processes = $ProcessesPerChain
                    ParameterFile = $parameterPath
                    ParameterSHA256 = $parameterHash
                    JobDirectory = $jobDirectory
                }
                $index++
            }
        }
    }
    $rows | Export-Csv -LiteralPath $manifestPath -NoTypeInformation -Encoding UTF8
    return @($rows)
}

if ($Mode -eq 'Prepare') {
    if (Test-Path -LiteralPath $manifestPath) { throw "Audit manifest already exists: $manifestPath. Choose a new AuditName." }
    $jobs = @(New-AuditManifest)
}
elseif ($Mode -eq 'Fresh') {
    if (Test-Path -LiteralPath $manifestPath -PathType Leaf) {
        $jobs = @(Import-Csv -LiteralPath $manifestPath)
    }
    else {
        $jobs = @(New-AuditManifest)
    }
}
else {
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) { throw "Audit manifest not found: $manifestPath. Run -Mode Fresh first." }
    $jobs = @(Import-Csv -LiteralPath $manifestPath)
}

$totalRanks = ($jobs | Measure-Object -Property Processes -Sum).Sum
if ($totalRanks -gt 24) { throw "This batch requests $totalRanks MPI ranks, exceeding the desktop's 24 physical cores. Split the grid or lower ProcessesPerChain." }

Write-Host "Audit=$safeName, mode=$Mode, jobs=$($jobs.Count), total MPI ranks=$totalRanks"
Write-Host "Manifest: $manifestPath"
if ($Mode -eq 'Prepare') { return }

$runLabel = if ($Mode -eq 'Production') { 'production_{0:D2}' -f $ProductionIndex } else { '{0}_{1}' -f $Mode.ToLowerInvariant(), (Get-Date -Format 'yyyyMMdd_HHmmss') }
$normalizedJobRoot = [IO.Path]::GetFullPath($jobRoot).TrimEnd('\') + '\'
$normalizedParameterRoot = [IO.Path]::GetFullPath($parameterDirectory).TrimEnd('\') + '\'
if (@($jobs.JobName | Select-Object -Unique).Count -ne $jobs.Count) { throw 'Manifest contains duplicate job names.' }
if (@($jobs.JobDirectory | Select-Object -Unique).Count -ne $jobs.Count) { throw 'Manifest contains duplicate job directories.' }

$preflightFailures = @()
foreach ($job in $jobs) {
    $jobDirectory = [IO.Path]::GetFullPath([string]$job.JobDirectory)
    $parameterPath = [IO.Path]::GetFullPath([string]$job.ParameterFile)
    $processCount = 0
    if (-not [int]::TryParse([string]$job.Processes, [ref]$processCount) -or $processCount -lt 1 -or $processCount -gt 24) {
        $preflightFailures += "Invalid process count for $($job.JobName): $($job.Processes)"
    }
    if (-not $jobDirectory.StartsWith($normalizedJobRoot, [StringComparison]::OrdinalIgnoreCase)) {
        $preflightFailures += "Job directory is outside this audit root: $jobDirectory"
    }
    if (-not $parameterPath.StartsWith($normalizedParameterRoot, [StringComparison]::OrdinalIgnoreCase)) {
        $preflightFailures += "Parameter file is outside this audit root: $parameterPath"
    }
    if (-not (Test-Path -LiteralPath $parameterPath -PathType Leaf)) {
        $preflightFailures += "Parameter file not found: $parameterPath"
    }
    else {
        if ($job.PSObject.Properties.Name -notcontains 'ParameterSHA256' -or -not [string]$job.ParameterSHA256) {
            $preflightFailures += "Manifest lacks a parameter hash for $($job.JobName); create a new audit name with the current runner."
        }
        else {
            $actualHash = (Get-FileHash -LiteralPath $parameterPath -Algorithm SHA256).Hash
            if ($actualHash -ne [string]$job.ParameterSHA256) {
                $preflightFailures += "Parameter file changed after manifest creation: $parameterPath"
            }
        }
    }
    if ($Mode -eq 'Fresh') {
        if (Test-Path -LiteralPath $jobDirectory) {
            $preflightFailures += "Fresh job directory already exists: $jobDirectory"
        }
    }
    else {
        if (-not (Test-Path -LiteralPath $jobDirectory -PathType Container)) {
            $preflightFailures += "Job directory not found: $jobDirectory"
        }
        elseif ($processCount -ge 1) {
            foreach ($rank in 0..($processCount - 1)) {
                $checkpoint = Join-Path $jobDirectory 'checkpoint.clone.h5'
                if ($rank -gt 0) { $checkpoint += ".$rank" }
                if (-not (Test-Path -LiteralPath $checkpoint -PathType Leaf)) {
                    $preflightFailures += "Checkpoint not found: $checkpoint"
                }
            }
        }
        if ($Mode -eq 'Production') {
            $savedResult = Join-Path $jobDirectory "$runLabel.out.h5"
            if (Test-Path -LiteralPath $savedResult) {
                $preflightFailures += "Production block already exists: $savedResult"
            }
        }
    }
}
if ($preflightFailures.Count -gt 0) {
    throw ('Audit preflight failed:' + [Environment]::NewLine + ($preflightFailures -join [Environment]::NewLine))
}

$processes = @()
foreach ($job in $jobs) {
    $jobDirectory = [string]$job.JobDirectory
    if ($Mode -eq 'Fresh') {
        if (Test-Path -LiteralPath $jobDirectory) { throw "Fresh job directory already exists: $jobDirectory" }
        New-Item -ItemType Directory -Path $jobDirectory | Out-Null
    }
    elseif (-not (Test-Path -LiteralPath $jobDirectory -PathType Container)) {
        throw "Job directory not found: $jobDirectory"
    }

    $savedResult = Join-Path $jobDirectory "$runLabel.out.h5"
    if ($Mode -eq 'Production' -and (Test-Path -LiteralPath $savedResult)) { throw "Production block already exists: $savedResult" }
    $stdout = Join-Path $jobDirectory "$runLabel.stdout.log"
    $stderr = Join-Path $jobDirectory "$runLabel.stderr.log"
    $arguments = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $runner, '-Ensemble', 'GrandCanonical', '-Mode', $Mode, '-Processes', [string]$job.Processes, '-ParameterFile', [string]$job.ParameterFile, '-OutputDirectory', $jobDirectory)
    $process = Start-Process -FilePath 'powershell.exe' -ArgumentList $arguments -WindowStyle Hidden -RedirectStandardOutput $stdout -RedirectStandardError $stderr -PassThru
    $processes += [pscustomobject]@{ Job=$job; Process=$process; Stdout=$stdout; Stderr=$stderr; SavedResult=$savedResult }
    Write-Host "Started $($job.JobName), PID=$($process.Id)"
}

$processes.Process | Wait-Process
$failures = @()
foreach ($entry in $processes) {
    $entry.Process.Refresh()
    $exitCode = $entry.Process.ExitCode
    Write-Host "Finished $($entry.Job.JobName), exit=$exitCode"
    if ($exitCode -ne 0) {
        $tail = if (Test-Path -LiteralPath $entry.Stderr) { (Get-Content -LiteralPath $entry.Stderr -Tail 20) -join [Environment]::NewLine } else { 'No stderr log was created.' }
        $failures += "$($entry.Job.JobName) exited $exitCode$([Environment]::NewLine)$tail"
        continue
    }
    if ($Mode -eq 'Production') {
        $currentResult = Join-Path ([string]$entry.Job.JobDirectory) 'result.out.h5'
        Copy-Item -LiteralPath $currentResult -Destination $entry.SavedResult
    }
}

if ($failures.Count -gt 0) {
    $separator = [Environment]::NewLine + [Environment]::NewLine
    throw ('One or more audit jobs failed:' + $separator + ($failures -join $separator))
}
Write-Host "Completed $Mode for all $($jobs.Count) jobs."
